[tool.poetry]
name = "pysembench"
version = "0.1.0"
description = ""
authors = ["bulricht <108867473+bulricht@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pysubyt = {git = "https://github.com/vliz-be-opsci/pysubyt.git", rev = "main"}


[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.1.0"
flake8 = "^6.0.0"
pytest = "^7.2.1"
sphinx = "^6.1.3"

[build-system]
requires = ["setuptools","poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true