[tool.poetry]
name = "pysembench"
version = "0.1.0"
description = ""
authors = ["bulricht <108867473+bulricht@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pysubyt = {git = "https://github.com/vliz-be-opsci/pysubyt.git", rev = "main"}


[tool.poetry.group.dev.dependencies]
pytest = {version = "^7.3.1", extras = ["dev"]}
sphinx = {version = "^7.0.1", extras = ["dev"]}
poetry = {version = "^1.4.2", extras = ["dev"]}
pre-commit = {version = "^3.3.1", extras = ["dev"]}
isort = {version = "^5.12.0", extras = ["dev"]}
black = {version = "^23.3.0", extras = ["dev"]}
flake8 = {version = "^6.0.0", extras = ["dev"]}
coverage = {version = "^7.2.5", extras = ["dev"]}

[tool.poetry.extras]
dev = []


[build-system]
requires = ["setuptools","poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
include_trailing_comma = true